// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbbmkdasswsxtbgwceja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYm1rZGFzc3dzeHRiZ3djZWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjEwNDksImV4cCI6MjA3MzkzNzA0OX0.c2iq67yRjwpJHisB3qX5FPVj6BgIkMnzc78hJbQhZSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});